const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Timeline,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Audio: 0},
	{Tween: 0},
	{Nala: 0},
	{Sine: 0},
	{Matahari: 0},
	{Langit: 0},
	{Awan: 0},
	{Sekolah: 0},
	{Halaman: 0},
	{Pohon: 0},
	{Pohon2: 0},
	{Pohon3: 0},
	{Rumput: 0},
	{Rumput2: 0},
	{TimelineController: 0},
	{PetualanganNalaMenjagaSekolahku: 0},
	{Plang: 0},
	{Sampah: 0},
	{NalaKaget: 0},
	{Keran: 0},
	{Pipa: 0},
	{PipaBelok: 0},
	{PercikanAir: 0},
	{GenanganAir: 0},
	{Btn_Bersihkan: 0},
	{Btn_Biarkan: 0},
	{Nala2: 0},
	{NalaSedih: 0},
	{Btn_TutupKeran: 0},
	{Btn_BiarkanKeran: 0},
	{Sprite: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Nala: class extends self.ISpriteInstance {},
	Matahari: class extends self.ISpriteInstance {},
	Langit: class extends self.ISpriteInstance {},
	Awan: class extends self.ISpriteInstance {},
	Sekolah: class extends self.ISpriteInstance {},
	Halaman: class extends self.ISpriteInstance {},
	Pohon: class extends self.ISpriteInstance {},
	Pohon2: class extends self.ISpriteInstance {},
	Pohon3: class extends self.ISpriteInstance {},
	Rumput: class extends self.ISpriteInstance {},
	Rumput2: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	PetualanganNalaMenjagaSekolahku: class extends self.ITextInstance {},
	Plang: class extends self.ISpriteInstance {},
	Sampah: class extends self.ISpriteInstance {},
	NalaKaget: class extends self.ISpriteInstance {},
	Keran: class extends self.ISpriteInstance {},
	Pipa: class extends self.ISpriteInstance {},
	PipaBelok: class extends self.ISpriteInstance {},
	PercikanAir: class extends self.ISpriteInstance {},
	GenanganAir: class extends self.ISpriteInstance {},
	Btn_Bersihkan: class extends self.ITextInstance {},
	Btn_Biarkan: class extends self.ITextInstance {},
	Nala2: class extends self.ISpriteInstance {},
	NalaSedih: class extends self.ISpriteInstance {},
	Btn_TutupKeran: class extends self.ITextInstance {},
	Btn_BiarkanKeran: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {}
}